---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitao.li.
--- DateTime: 2023/5/4 5:34 PM
---
require "Framework.Common.BaseClass"
local BaseBlock = require "UnitTest.BaseBlock"

local RainbowBlock = BaseClass("RainbowBlock", BaseBlock)

--------------------------需要序列化的数据--------------------------
RainbowBlock:AddDefineList({
    {name = "colorList", type = CS.System.Collections.Generic.List(typeof(CS.UnityEngine.UI.Image))},

})
--在编辑器下只加载DefineList,不管其他部分
if ExecuteInEditorScript then
    return RainbowBlock
end
--------------------------需要序列化的数据--------------------------

function RainbowBlock:initialize()
    BaseBlock.initialize(self)
    

end

return RainbowBlock

