---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitao.li.
--- DateTime: 2023/5/15 9:44 AM
---

local GameConfig = {}

GameConfig.blockWidth = 97
GameConfig.blockHeight = 97
GameConfig.blockLength = 93;
GameConfig.blockImageHeight = 94;

GameConfig.GroupInitScale = Vector3.New(0.5, 0.5, 0.5);

GameConfig.BottomWidth = 750;
GameConfig.GroupClickYAdd = 300
GameConfig.GroupMoveSpeed = 1.0


return ConstClass("GameConfig", GameConfig)