---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitao.li.
--- DateTime: 2023/5/4 6:08 PM
---
require "Framework.Common.BaseClass"
local LuaBehaviour = require "Framework.Common.LuaBehaviour"

local BaseBlock = BaseClass("BaseBlock", LuaBehaviour)

--------------------------需要序列化的数据--------------------------
BaseBlock:AddDefineList({
    {name = "Block", type = CS.UnityEngine.UI.Image},
})
--在编辑器下只加载DefineList,不管其他部分
if ExecuteInEditorScript then
    return BaseBlock
end
--------------------------需要序列化的数据--------------------------

function BaseBlock:initialize()
    LuaBehaviour.initialize(self)

end

function BaseBlock:OnEnable()
    print("OnEnable")
end

return BaseBlock

