---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitao.li.
--- DateTime: 2023/5/4 6:09 PM
---
require "Framework.Common.BaseClass"
local BaseBlock = require "GameLogic.HomeScene.Block"

local RainbowBlock = BaseClass("RainbowBlock", BaseBlock)

--------------------------需要序列化的数据--------------------------
RainbowBlock:AddDefineList({
    {name = "Label1", type = CS.TMPro.TextMeshProUGUI},
})
--在编辑器下只加载DefineList,不管其他部分
if ExecuteInEditorScript then
    return RainbowBlock
end
--------------------------需要序列化的数据--------------------------

function RainbowBlock:initialize()
    BaseBlock.initialize(self)
end

return RainbowBlock

