---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitaoli.
--- DateTime: 2023/3/27 16:32
---

local BlockConfig = {}

BlockConfig.Block = "UI/Prefabs/MainScene/Block/Block.prefab"
BlockConfig.BlockGroup = "UI/Prefabs/MainScene/BlockGroup/BlockGroup.prefab"




return ConstClass("BlockConfig", BlockConfig)
