---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitao.li.
--- DateTime: 2023/5/4 6:02 PM
---
require "Framework.Common.BaseClass"
local LuaBehaviour = require "Framework.Common.LuaBehaviour"

local BlockGroup = BaseClass("BlockGroup", LuaBehaviour)

--------------------------需要序列化的数据--------------------------
BlockGroup:AddDefineList({
})
--在编辑器下只加载DefineList,不管其他部分
if ExecuteInEditorScript then
    return BlockGroup
end
--------------------------需要序列化的数据--------------------------

local BlockData = require "Config.Data.BlockData"


function BlockGroup:initialize()
    LuaBehaviour.initialize(self)

end

function BlockGroup:OnStart()
    print("OnStart")
end

function BlockGroup:Start(blockGroupDataId)

    if BlockData[blockGroupDataId].id == nil then
        print("BlockGroupData index  " .. blockGroupDataId .. "不存在")
        blockGroupDataId = 1;
    end

    self.BlockGroupData = BlockData[blockGroupDataId];
    self:createBlock();

end

function BlockGroup:createBlock()
    local blockArray = self.BlockGroupData.data;
    print("BlockGroup tableLength = " ..  #blockArray)
end


function BlockGroup:OnDisable()
    print("OnDisable")
end

function BlockGroup:OnDestroy()
    print("OnDestroy")
end




return BlockGroup

