---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitaoli.
--- DateTime: 2023/6/11 08:15
---

require "Framework.Common.BaseClass"
local LuaBehaviour = require "Framework.Common.LuaBehaviour"

local Board = BaseClass("Board", LuaBehaviour)

--------------------------需要序列化的数据--------------------------
Board:AddDefineList({
})
--在编辑器下只加载DefineList,不管其他部分
if ExecuteInEditorScript then
    return Board
end
--------------------------需要序列化的数据--------------------------

function Board:__init()
    print("------------ Board init")
    self.UIRoot = nil;
end

function Board:initialize()
    LuaBehaviour.initialize(self)
end

function Board:OnStart()
    local rootObj = BlockUtil.FindGameObjectInCanvas("UIRoot");
    if rootObj then
        print("UIRoot found")
        self.UIRoot = rootObj.transform
    else
        print("UIRoot not found")
    end
end



function Board:Update()
    if GameSceneControl:GetInstance().checkedGroup ~= nil then
        self:judgeClear()
    end
end

function Board:judgeClear()

    local blockGroup = GameSceneControl:GetInstance().checkedGroup
    
    local worldPosition = BlockUtil.ConvertLocalPosition(blockGroup.blockList[1].transform, self.UIRoot);

    print("世界坐标" .. "x = ".. worldPosition.x .. "y = " .. worldPosition.y)
end



return Board
