---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitaoli.
--- DateTime: 2023/6/11 08:15
---

require "Framework.Common.BaseClass"
local LuaBehaviour = require "Framework.Common.LuaBehaviour"

local Board = BaseClass("Board", LuaBehaviour)

--------------------------需要序列化的数据--------------------------
Board:AddDefineList({
})
--在编辑器下只加载DefineList,不管其他部分
if ExecuteInEditorScript then
    return Board
end
--------------------------需要序列化的数据--------------------------



function Board:initialize()
LuaBehaviour.initialize(self)

end



function Board:Update()
    if GameSceneControl:GetInstance():getCheckedGroup() ~= nil then
        this.judgeClear()
    end
end

function Board:judgeClear()
    
end



return Board
