---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitaoli.
--- DateTime: 2023/6/11 15:23
---

local GameSceneControl = BaseClass("GameSceneControl", Singleton)

function GameSceneControl:__init()
    print("------------ GameSceneControl init")
    self.checkedGroup = nil;
end

function GameSceneControl:CheckedGroup(blockGroup)
    if self.checkedGroup ~= nil then
        print("当前有选中的BlockGroup，不能重复设置")
    end
    
    print("设置选中BlockGroup")
    self.checkedGroup = blockGroup;
end

function GameSceneControl:UnCheckedGroup(bockGroup)
    self.checkedGroup = nil;
end

return GameSceneControl
