---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitaoli.
--- DateTime: 2023/3/13 20:27
---
require "Framework.Common.BaseClass"
local LuaBehaviour = require "Framework.LuaBehaviour.LuaBehaviour"

local RotateButton = BaseClass("RotateButton", LuaBehaviour)

--------------------------需要序列化的数据--------------------------
RotateButton:AddDefineList({
    {name = "Label", type = CS.TMPro.TextMeshProUGUI},
})
--在编辑器下只加载DefineList,不管其他部分
if ExecuteInEditorScript then return RotateButton end
--------------------------需要序列化的数据--------------------------

function RotateButton:initialize()
    --LuaBehaviour的构造函数
    LuaBehaviour.initialize(self)
    --输出注入的对象
    for key, value in pairs(self) do
        print("key : "..key..", value : "..tostring(value))
    end
    
    self.Label.text = "x0"
    
end

function RotateButton:OnEnable()
    print("RotateButton OnEnable")
end

function RotateButton:Update()
    print("RotateButton Update")

end
--[[
function LuaBehaviourTest:FixedUpdate()
    print("FixedUpdate")
end

function LuaBehaviourTest:LateUpdate()
    print("LateUpdate")
end
]]--

function RotateButton:OnPointerClick(eventData)
    print("RotateButton click pos : "..tostring(eventData.position))
end

function RotateButton:OnDisable()
    print("RotateButton OnDisable")
end

function RotateButton:OnDestroy()
    print("RotateButton OnDestroy")
end

return RotateButton