---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitao.li.
--- DateTime: 2023/5/9 5:02 PM
---
package.cpath = package.cpath .. ';/Users/haitao.li/Library/Application Support/JetBrains/Rider2021.3/plugins/EmmyLua/debugger/emmy/mac/x64/?.dylib'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 9966)