---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haitaoli.
--- DateTime: 2023/4/1 09:11
--- block 配置表
local BlockData = {
    [1] = {
        id = 1,
        group = 1,
        count = 4,
        data = {{0,0,1,0,0},{0,0,1,0,0},{0,0,1,0,0},{0,0,1,0,0},{0,0,0,0,0,0}}
    },
    [2] = {
        id = 2,
        group = 1,
        count = 4,
        data = {{0,0,0,0,0},{0,0,0,0,0},{1,1,1,1,1},{0,0,0,0,0},{0,0,0,0,0,0}}
    },
    [3] = {
        id = 3,
        group = 1,
        count = 4,
        data = {{0,1,1,0,0},{0,1,1,0,0},{0,0,0,0,0},{0,0,0,0,0},{0,0,0,0,0,0}}
    },
    [4] = {
        id = 4,
        group = 1,
        count = 4,
        data = {{0,1,1,0,0},{0,0,0,0,0},{0,0,0,0,0},{0,0,0,0,0},{0,0,0,0,0,0}}
    },
}
return BlockData